require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Agrobot' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'

  pod 'react-native-slider', :path => '../node_modules/@react-native-community/slider'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNCMaskedView', :path => '../node_modules/@react-native-masked-view/masked-view'

  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  pod 'react-native-orientation', :path => '../node_modules/react-native-orientation'

  pod 'RNCPicker', :path => '../node_modules/@react-native-community/picker'

  pod 'react-native-document-picker', :path => '../node_modules/react-native-document-picker'

  target 'AgrobotTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'Agrobot-tvOS' do
  # Pods for Agrobot-tvOS

  target 'Agrobot-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
